version: '3'
services:
  both:
    build:
      context: .
      dockerfile: Dockerfile
    image: eis-app
    container_name: eis-app-both
    volumes:
      - ./output:/app/output
    command: [
      "both",
      "-s", "theguardian",
      "-q", "nuclear power",
      "-f", "2022-01-01",
      "-t", "2023-01-01",
      "-o", "output/data",
      "-ca", "1000",
      "-ct", "1000",
      "-k", "***REMOVED***"
    ]