version: '3'
services:
  eis-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eis-app-image
    container_name: eis-app-container
    volumes:
      - ./output:/app/output
    command: >
      both
      --source theguardian
      --query nuclear power
      --from 2022-01-01
      --to 2023-01-01
      --output-articles output/articles.json
      --output-terms output/terms.json
      --count-articles 100
      --count-terms 100
      --api-key <API_KEY>